namespace ToonNet.SourceGenerators;

/// <summary>
/// Internal marker interface injected by the ToonSerializable source generator.
/// Represents a class that supports TOON serialization through source-generated methods.
/// </summary>
/// <remarks>
/// This interface is intended for internal use and should not be implemented or accessed
/// directly in application code. It serves as a mechanism for runtime detection of
/// serialization functionality generated by the ToonSerializable source generator.
/// </remarks>

internal interface IToonSerializable
{
    // This interface has no members.
    // Its presence indicates that the class has generated Serialize/Deserialize methods.
}