using Microsoft.CodeAnalysis.CSharp;
using ToonNet.SourceGenerators.Model;
using ToonNet.SourceGenerators.Utilities;

namespace ToonNet.SourceGenerators;

/// <summary>
/// Writes the generated partial type with its static <c>Serialize</c> and <c>Deserialize</c> methods.
/// </summary>
/// <remarks>
/// Strings, booleans and numbers are converted inline when no converters are registered in the options; every other
/// value goes through <c>ToonSerializer.SerializeToValue</c> / <c>DeserializeFromValue</c>, so the output and the
/// accepted input are the same as with the reflection-based serializer.
/// </remarks>
internal static class SourceEmitter
{
    private const string Models = "global::ToonNet.Core.Models.";
    private const string Serialization = "global::ToonNet.Core.Serialization.";
    private const string Serializer = Serialization + "ToonSerializer";
    private const string Options = Serialization + "ToonSerializerOptions";

    public static string Emit(TypeModel model)
    {
        var code = new CodeBuilder();

        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable annotations");
        code.AppendLine("#nullable disable warnings");
        code.AppendLine("#pragma warning disable CS0612, CS0618 // Obsolete members are serialized like any other");
        code.AppendLine();

        if (model.Namespace != null)
        {
            code.AppendLine($"namespace {model.Namespace};");
            code.AppendLine();
        }

        foreach (var containing in model.ContainingTypeDeclarations)
        {
            code.BeginBlock(containing);
        }

        if (model.Documentation)
        {
            code.AppendLine("/// <summary>");
            code.AppendLine("/// Generated TOON serialization methods.");
            code.AppendLine("/// </summary>");
        }

        code.BeginBlock(model.Declaration);

        EmitConverterFields(code, model);
        EmitSerialize(code, model);

        if (model.Constructor != null)
        {
            code.AppendLine();
            EmitDeserialize(code, model, model.Constructor);
            EmitAccessors(code, model);
        }

        code.EndBlock();

        foreach (var _ in model.ContainingTypeDeclarations)
        {
            code.EndBlock();
        }

        return code.ToString();
    }

    private static void EmitConverterFields(CodeBuilder code, TypeModel model)
    {
        var any = false;

        foreach (var property in model.Properties)
        {
            if (property.ConverterTypeName == null)
            {
                continue;
            }

            code.AppendLine($"private static readonly {Serialization}IToonConverter {ConverterField(property)} = new {property.ConverterTypeName}();");
            any = true;
        }

        if (any)
        {
            code.AppendLine();
        }
    }

    private static void EmitSerialize(CodeBuilder code, TypeModel model)
    {
        if (model.Documentation)
        {
            code.AppendLine("/// <summary>");
            code.AppendLine("/// Converts an instance to a TOON document, with the same output as <see cref=\"global::ToonNet.Core.Serialization.ToonSerializer\"/>.");
            code.AppendLine("/// </summary>");
            code.AppendLine("/// <param name=\"value\">The instance to serialize.</param>");
            code.AppendLine("/// <param name=\"options\">Serialization options (defaults when null).</param>");
            code.AppendLine("/// <returns>A TOON document whose root is an object.</returns>");
        }

        code.BeginBlock($"{Accessibility(model)} static {Models}ToonDocument Serialize({model.FullyQualifiedName} value, {Options}? options = null)");

        if (model.NullChecks && !model.IsValueType)
        {
            code.AppendLine("global::System.ArgumentNullException.ThrowIfNull(value);");
        }

        code.AppendLine($"options ??= {Options}.Default;");
        code.AppendLine("var __inline = options.Converters.Count == 0;");
        EmitPolicyLocal(code, model);
        code.AppendLine($"var __obj = new {Models}ToonObject();");

        for (var i = 0; i < model.Properties.Length; i++)
        {
            var property = model.Properties[i];
            var name = NameExpression(property, model);
            var local = $"__v{i}";

            code.AppendLine();
            code.AppendLine($"// {property.Name}");
            code.BeginBlock(property.IsReadOnly ? "if (options.IncludeReadOnlyProperties)" : "");
            code.AppendLine($"var {local} = value.{property.Name};");

            if (property.CanBeNull)
            {
                code.BeginBlock($"if ({local} is null)");
                code.AppendLine($"if (!options.IgnoreNullValues) __obj.Properties[{name}] = {Models}ToonNull.Instance;");
                code.EndBlock();
                code.BeginBlock("else");
                EmitWrite(code, property, name, local, property.IsNullableValueType ? $"{local}.GetValueOrDefault()" : local, i);
                code.EndBlock();
            }
            else
            {
                EmitWrite(code, property, name, local, local, i);
            }

            code.EndBlock();
        }

        code.AppendLine();
        code.AppendLine($"return new {Models}ToonDocument(__obj);");
        code.EndBlock();
    }

    private static void EmitWrite(CodeBuilder code, PropertyModel property, string name, string local, string nonNull, int index)
    {
        if (property.ConverterTypeName != null)
        {
            code.AppendLine($"var __t{index} = {ConverterField(property)}.Write({local}, options);");
            code.AppendLine($"if (__t{index} is not null) __obj.Properties[{name}] = __t{index};");
            return;
        }

        var reflection = $"{Serializer}.SerializeToValue<{property.TypeName}>({local}, options)";

        var inline = property.Primitive switch
        {
            PrimitiveKind.String => $"new {Models}ToonString({nonNull})",
            PrimitiveKind.Boolean => $"new {Models}ToonBoolean({nonNull})",
            PrimitiveKind.Integer => $"new {Models}ToonNumber((long){nonNull})",
            PrimitiveKind.None => null,
            _ => $"new {Models}ToonNumber({nonNull})"
        };

        code.AppendLine(inline == null
                            ? $"__obj.Properties[{name}] = {reflection};"
                            : $"__obj.Properties[{name}] = __inline ? {inline} : {reflection};");
    }

    private static void EmitDeserialize(CodeBuilder code, TypeModel model, ConstructorModel constructor)
    {
        if (model.Documentation)
        {
            code.AppendLine("/// <summary>");
            code.AppendLine("/// Creates an instance from a TOON document, following the rules of <see cref=\"global::ToonNet.Core.Serialization.ToonSerializer\"/>.");
            code.AppendLine("/// </summary>");
            code.AppendLine("/// <param name=\"doc\">The TOON document to deserialize.</param>");
            code.AppendLine("/// <param name=\"options\">Deserialization options (defaults when null).</param>");
            code.AppendLine("/// <returns>A new instance populated from the document.</returns>");
        }

        code.BeginBlock($"{Accessibility(model)} static {model.FullyQualifiedName} Deserialize({Models}ToonDocument doc, {Options}? options = null)");

        if (model.NullChecks)
        {
            code.AppendLine("global::System.ArgumentNullException.ThrowIfNull(doc);");
        }

        code.AppendLine($"options ??= {Options}.Default;");
        code.AppendLine();
        code.BeginBlock($"if (doc.Root is not {Models}ToonObject __obj)");
        code.AppendLine("// Let the serializer report the mismatch (or return null for a null root).");
        code.AppendLine($"return {Serializer}.DeserializeFromValue<{model.FullyQualifiedName}>(doc.Root, options)!;");
        code.EndBlock();
        code.AppendLine();
        code.AppendLine("var __inline = options.Converters.Count == 0;");
        EmitPolicyLocal(code, model);

        var arguments = new List<string>();

        for (var j = 0; j < constructor.Parameters.Length; j++)
        {
            var parameter = constructor.Parameters[j];
            var bound = parameter.PropertyIndex >= 0 ? model.Properties[parameter.PropertyIndex] : null;
            var key = bound != null ? NameExpression(bound, model) : SymbolDisplay.FormatLiteral(parameter.Name, true);
            var read = bound?.ConverterTypeName != null
                ? $"({parameter.TypeName}){ConverterField(bound)}.Read(__ta{j}, typeof({bound.TypeOfName}), options)!"
                : $"{Serializer}.DeserializeFromValue<{parameter.TypeName}>(__ta{j}, options)!";

            code.AppendLine();
            code.AppendLine($"{parameter.TypeName} __a{j} = {parameter.DefaultValue};");
            code.AppendLine($"if (__obj.Properties.TryGetValue({key}, out var __ta{j})) __a{j} = {read};");
            arguments.Add($"__a{j}");
        }

        for (var i = 0; i < model.Properties.Length; i++)
        {
            var property = model.Properties[i];

            if (property.Write == WriteKind.None)
            {
                continue;
            }

            code.AppendLine();
            code.AppendLine($"{property.TypeName} __p{i} = default!;");
            code.AppendLine($"var __h{i} = false;");
            code.BeginBlock($"if (__obj.Properties.TryGetValue({NameExpression(property, model)}, out var __t{i}))");
            code.AppendLine($"__p{i} = {ReadExpression(property, $"__t{i}", i)};");
            code.AppendLine($"__h{i} = true;");
            code.EndBlock();
        }

        code.AppendLine();

        var initializers = model.Properties.Select((p, i) => (Property: p, Index: i))
                                .Where(p => p.Property.Write == WriteKind.Initializer)
                                .Select(p => $"{p.Property.Name} = __h{p.Index} ? __p{p.Index} : default!")
                                .ToList();

        var creation = $"new {model.FullyQualifiedName}({string.Join(", ", arguments)})";

        if (initializers.Count == 0)
        {
            code.AppendLine($"var __result = {creation};");
        }
        else
        {
            code.AppendLine($"var __result = {creation}");
            code.AppendLine("{");
            code.IncrementIndent();

            foreach (var initializer in initializers)
            {
                code.AppendLine(initializer + ",");
            }

            code.DecrementIndent();
            code.AppendLine("};");
        }

        for (var i = 0; i < model.Properties.Length; i++)
        {
            var property = model.Properties[i];

            switch (property.Write)
            {
                case WriteKind.Assign:
                    code.AppendLine($"if (__h{i}) __result.{property.Name} = __p{i};");
                    break;
                case WriteKind.Accessor:
                    var reference = property.SetterOwnerIsValueType ? "ref " : "";
                    code.AppendLine($"if (__h{i}) {AccessorName(property)}({reference}__result, __p{i});");
                    break;
            }
        }

        code.AppendLine();
        code.AppendLine("return __result;");
        code.EndBlock();
    }

    /// <summary>
    /// Reads a property value: an inline fast path for exact string, boolean and number matches, otherwise the
    /// serializer (which also produces the error message for values that do not fit).
    /// </summary>
    private static string ReadExpression(PropertyModel property, string toon, int index)
    {
        if (property.ConverterTypeName != null)
        {
            return $"({property.TypeName}){ConverterField(property)}.Read({toon}, typeof({property.TypeOfName}), options)!";
        }

        var reflection = $"{Serializer}.DeserializeFromValue<{property.TypeName}>({toon}, options)!";
        var type = property.PrimitiveTypeName;
        var d = $"__d{index}";
        var n = $"__n{index}";
        var exactNumber = $"{toon} is {Models}ToonNumber {{ DecimalValue: {{ }} {d} }}";

        var (condition, value) = property.Primitive switch
        {
            PrimitiveKind.String => ($"{toon} is {Models}ToonString __s{index}", $"__s{index}.Value"),
            PrimitiveKind.Boolean => ($"{toon} is {Models}ToonBoolean __b{index}", $"__b{index}.Value"),
            PrimitiveKind.Integer or PrimitiveKind.UInt64 =>
                ($"{exactNumber} && {d} == decimal.Truncate({d}) && {d} >= {type}.MinValue && {d} <= {type}.MaxValue", $"({type}){d}"),
            PrimitiveKind.Decimal => (exactNumber, d),
            PrimitiveKind.Double => ($"{toon} is {Models}ToonNumber {n}", $"{n}.Value"),
            PrimitiveKind.Single => ($"{toon} is {Models}ToonNumber {n}", $"(float){n}.Value"),
            _ => (null, null)
        };

        return condition == null ? reflection : $"__inline && {condition} ? {value} : {reflection}";
    }

    private static void EmitAccessors(CodeBuilder code, TypeModel model)
    {
        foreach (var property in model.Properties)
        {
            if (property.Write != WriteKind.Accessor)
            {
                continue;
            }

            var reference = property.SetterOwnerIsValueType ? "ref " : "";

            code.AppendLine();
            code.AppendLine("[global::System.Runtime.CompilerServices.UnsafeAccessor(" +
                            $"global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = \"set_{property.Name}\")]");
            code.AppendLine($"private static extern void {AccessorName(property)}({reference}{property.SetterOwner} instance, {property.TypeName} value);");
        }
    }

    private static void EmitPolicyLocal(CodeBuilder code, TypeModel model)
    {
        if (model.FixedNamingPolicy == null)
        {
            code.AppendLine("var __policy = options.PropertyNamingPolicy;");
        }
    }

    /// <summary>
    /// The serialized key: the <c>[ToonProperty]</c> name, the attribute's fixed naming policy, or the naming policy
    /// of the options at runtime.
    /// </summary>
    private static string NameExpression(PropertyModel property, TypeModel model)
    {
        var names = property.Names;

        if (model.FixedNamingPolicy is { } policy)
        {
            return Literal(names[policy is >= 0 and <= 3 ? policy : 0]);
        }

        if (names.Items.All(n => n == names[0]))
        {
            return Literal(names[0]);
        }

        const string policyType = Serialization + "PropertyNamingPolicy";

        if (names[1] == names[2] && names[2] == names[3])
        {
            return $"(__policy == {policyType}.Default ? {Literal(names[0])} : {Literal(names[1])})";
        }

        return $"(__policy switch {{ {policyType}.CamelCase => {Literal(names[1])}, {policyType}.SnakeCase => {Literal(names[2])}, " +
               $"{policyType}.LowerCase => {Literal(names[3])}, _ => {Literal(names[0])} }})";
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);

    private static string Accessibility(TypeModel model) => model.PublicMethods ? "public" : "internal";

    private static string ConverterField(PropertyModel property) => $"__ToonConverter_{property.Name}";

    private static string AccessorName(PropertyModel property) => $"__ToonSet_{property.Name}";
}
