using Microsoft.CodeAnalysis.CSharp;
using ToonNet.SourceGenerators.Model;
using ToonNet.SourceGenerators.Utilities;

namespace ToonNet.SourceGenerators;

/// <summary>
/// Writes the generated partial type: the public <c>Serialize</c>/<c>Deserialize</c> methods, the
/// <c>__ToonSerializeValue</c>/<c>__ToonDeserializeValue</c> methods other generated types call, and one helper
/// method per collection or dictionary type.
/// </summary>
/// <remarks>
/// Generated code runs only when the options contain no converters; otherwise (and for derived runtime types) it
/// defers to <c>ToonSerializer</c>, so the output is always the same as the reflection-based serializer's.
/// </remarks>
internal sealed class SourceEmitter
{
    private const string Models = "global::ToonNet.Core.Models.";
    private const string Serialization = "global::ToonNet.Core.Serialization.";
    private const string Serializer = Serialization + "ToonSerializer";
    private const string Helpers = Serialization + "ToonSourceGenerationHelpers";
    private const string Options = Serialization + "ToonSerializerOptions";
    private const string HiddenAttribute = "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";

    private readonly TypeModel _model;
    private readonly CodeBuilder _code = new();
    private readonly Dictionary<string, int> _writerIds = new(StringComparer.Ordinal);
    private readonly Dictionary<string, int> _readerIds = new(StringComparer.Ordinal);
    private readonly List<(int Id, ValuePlan Plan)> _writers = [];
    private readonly List<(int Id, ValuePlan Plan)> _readers = [];
    private int _variable;

    private SourceEmitter(TypeModel model) => _model = model;

    public static string Emit(TypeModel model) => new SourceEmitter(model).Run();

    private string Run()
    {
        var code = _code;

        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable annotations");
        code.AppendLine("#nullable disable warnings");
        code.AppendLine("#pragma warning disable CS0612, CS0618 // Obsolete members are serialized like any other");
        code.AppendLine();

        if (_model.Namespace != null)
        {
            code.AppendLine($"namespace {_model.Namespace};");
            code.AppendLine();
        }

        foreach (var containing in _model.ContainingTypeDeclarations)
        {
            code.BeginBlock(containing);
        }

        if (_model.Documentation)
        {
            code.AppendLine("/// <summary>");
            code.AppendLine("/// Generated TOON serialization methods.");
            code.AppendLine("/// </summary>");
        }

        code.BeginBlock(_model.Declaration);

        EmitConverterFields();
        EmitSerialize();

        if (_model.Constructor != null)
        {
            code.AppendLine();
            EmitDeserialize(_model.Constructor);
            EmitAccessors();
        }

        EmitHelperMethods();

        code.EndBlock();

        foreach (var _ in _model.ContainingTypeDeclarations)
        {
            code.EndBlock();
        }

        return code.ToString();
    }

    private void EmitConverterFields()
    {
        var any = false;

        foreach (var property in _model.Properties)
        {
            if (property.ConverterTypeName == null)
            {
                continue;
            }

            _code.AppendLine($"private static readonly {Serialization}IToonConverter {ConverterField(property)} = new {property.ConverterTypeName}();");
            any = true;
        }

        if (any)
        {
            _code.AppendLine();
        }
    }

    #region Serialize

    private void EmitSerialize()
    {
        var code = _code;
        var model = _model;

        if (model.Documentation)
        {
            code.AppendLine("/// <summary>");
            code.AppendLine("/// Converts an instance to a TOON document, with the same output as <see cref=\"global::ToonNet.Core.Serialization.ToonSerializer\"/>.");
            code.AppendLine("/// </summary>");
            code.AppendLine("/// <param name=\"value\">The instance to serialize.</param>");
            code.AppendLine("/// <param name=\"options\">Serialization options (defaults when null).</param>");
            code.AppendLine("/// <returns>A TOON document.</returns>");
        }

        code.BeginBlock($"{Accessibility()} static {Models}ToonDocument Serialize({model.FullyQualifiedName} value, {Options}? options = null)");

        if (model.NullChecks && !model.IsValueType)
        {
            code.AppendLine("global::System.ArgumentNullException.ThrowIfNull(value);");
        }

        code.AppendLine($"options ??= {Options}.Default;");
        code.AppendLine($"return new {Models}ToonDocument(__ToonSerializeValue(value, options, 0));");
        code.EndBlock();
        code.AppendLine();

        code.AppendLine("/// <summary>Used by generated code; call <c>Serialize</c> instead.</summary>");
        code.AppendLine(HiddenAttribute);
        code.BeginBlock($"public static {Models}ToonValue __ToonSerializeValue({model.FullyQualifiedName} value, {Options} options, int depth)");

        if (!model.IsValueType)
        {
            code.AppendLine($"if (value is null) return {Models}ToonNull.Instance;");
        }

        code.AppendLine($"{Helpers}.CheckSerializationDepth(options, depth);");

        var reflection = $"{Helpers}.SerializeWithReflection<{model.FullyQualifiedName}>(value, options, depth)";

        if (model.HasTypeConverter)
        {
            code.AppendLine($"return {reflection};");
            code.EndBlock();
            return;
        }

        var fallback = model.CheckRuntimeType
            ? $"options.Converters.Count != 0 || value.GetType() != typeof({model.TypeOfName})"
            : "options.Converters.Count != 0";

        code.AppendLine("// Converters and derived types are handled by ToonSerializer, which knows the runtime type.");
        code.AppendLine($"if ({fallback}) return {reflection};");
        EmitPolicyLocal();
        code.AppendLine($"var __obj = new {Models}ToonObject();");

        for (var i = 0; i < model.Properties.Length; i++)
        {
            var property = model.Properties[i];
            var name = NameExpression(property);
            var local = $"__v{i}";

            code.AppendLine();
            code.AppendLine($"// {property.Name}");
            code.BeginBlock(property.IsReadOnly ? "if (options.IncludeReadOnlyProperties)" : "");
            code.AppendLine($"var {local} = value.{property.Name};");

            if (property.ConverterTypeName != null)
            {
                EmitNullCheck(property.Plan, local, $"__obj.Properties[{name}]", () =>
                {
                    code.AppendLine($"var __t{i} = {ConverterField(property)}.Write({local}, options);");
                    code.AppendLine($"if (__t{i} is not null) __obj.Properties[{name}] = __t{i};");
                });
            }
            else
            {
                EmitStore($"__obj.Properties[{name}]", property.Plan, local, "depth + 1");
            }

            code.EndBlock();
        }

        code.AppendLine();
        code.AppendLine("return __obj;");
        code.EndBlock();
    }

    /// <summary>Stores a value in an object slot; nulls follow <c>IgnoreNullValues</c>, like ToonSerializer.</summary>
    private void EmitStore(string target, ValuePlan plan, string local, string depth)
    {
        EmitNullCheck(plan, local, target, () => _code.AppendLine($"{target} = {WriteExpression(plan, NonNull(plan, local), depth)};"));
    }

    private void EmitNullCheck(ValuePlan plan, string local, string target, Action write)
    {
        if (!plan.CanBeNull)
        {
            write();
            return;
        }

        _code.BeginBlock($"if ({local} is null)");
        _code.AppendLine($"if (!options.IgnoreNullValues) {target} = {Models}ToonNull.Instance;");
        _code.EndBlock();
        _code.BeginBlock("else");
        write();
        _code.EndBlock();
    }

    /// <summary>An expression converting a non-null value to a <c>ToonValue</c>.</summary>
    private string WriteExpression(ValuePlan plan, string value, string depth)
    {
        return plan.Kind switch
        {
            ValueKind.Inline => plan.Inline switch
            {
                PrimitiveKind.String => $"new {Models}ToonString({value})",
                PrimitiveKind.Boolean => $"new {Models}ToonBoolean({value})",
                PrimitiveKind.Integer => $"new {Models}ToonNumber((long){value})",
                _ => $"new {Models}ToonNumber({value})"
            },
            ValueKind.Primitive => $"{Helpers}.WritePrimitive<{plan.ValueTypeName}>({value})",
            ValueKind.Raw => value,
            ValueKind.Generated => $"{plan.ValueTypeName}.__ToonSerializeValue({value}, options, {depth})",
            ValueKind.Reflection => $"{Helpers}.SerializeWithReflection<{plan.ValueTypeName}>({value}, options, {depth})",
            _ => $"{WriterName(plan)}({value}, options, {depth})"
        };
    }

    private static string NonNull(ValuePlan plan, string local) => plan.IsNullableValueType ? $"{local}.GetValueOrDefault()" : local;

    #endregion

    #region Deserialize

    private void EmitDeserialize(ConstructorModel constructor)
    {
        var code = _code;
        var model = _model;

        if (model.Documentation)
        {
            code.AppendLine("/// <summary>");
            code.AppendLine("/// Creates an instance from a TOON document, following the rules of <see cref=\"global::ToonNet.Core.Serialization.ToonSerializer\"/>.");
            code.AppendLine("/// </summary>");
            code.AppendLine("/// <param name=\"doc\">The TOON document to deserialize.</param>");
            code.AppendLine("/// <param name=\"options\">Deserialization options (defaults when null).</param>");
            code.AppendLine("/// <returns>A new instance populated from the document.</returns>");
        }

        code.BeginBlock($"{Accessibility()} static {model.FullyQualifiedName} Deserialize({Models}ToonDocument doc, {Options}? options = null)");

        if (model.NullChecks)
        {
            code.AppendLine("global::System.ArgumentNullException.ThrowIfNull(doc);");
        }

        code.AppendLine($"options ??= {Options}.Default;");
        code.AppendLine("return __ToonDeserializeValue(doc.Root, options, 0);");
        code.EndBlock();
        code.AppendLine();

        code.AppendLine("/// <summary>Used by generated code; call <c>Deserialize</c> instead.</summary>");
        code.AppendLine(HiddenAttribute);
        code.BeginBlock($"public static {model.FullyQualifiedName} __ToonDeserializeValue({Models}ToonValue value, {Options} options, int depth)");
        code.AppendLine($"{Helpers}.CheckDeserializationDepth(options, depth);");

        var reflection = $"{Helpers}.DeserializeWithReflection<{model.FullyQualifiedName}>(value, options, depth)";

        if (model.HasTypeConverter)
        {
            code.AppendLine($"return {reflection};");
            code.EndBlock();
            return;
        }

        code.AppendLine("// Converters, null and non-object values are handled (or reported) by ToonSerializer.");
        code.AppendLine($"if (options.Converters.Count != 0 || value is not {Models}ToonObject __obj) return {reflection};");
        EmitPolicyLocal();

        var arguments = new List<string>();

        for (var j = 0; j < constructor.Parameters.Length; j++)
        {
            var parameter = constructor.Parameters[j];
            var bound = parameter.PropertyIndex >= 0 ? model.Properties[parameter.PropertyIndex] : null;
            var key = bound != null ? NameExpression(bound) : Literal(parameter.Name);
            var read = bound?.ConverterTypeName != null
                ? $"({parameter.TypeName}){ConverterField(bound)}.Read(__ta{j}, typeof({bound.TypeOfName}), options)"
                : ReadExpression(parameter.Plan, $"__ta{j}", "depth + 1");

            code.AppendLine();
            code.AppendLine($"{parameter.TypeName} __a{j} = {parameter.DefaultValue};");
            code.AppendLine($"if (__obj.Properties.TryGetValue({key}, out var __ta{j})) __a{j} = {read};");
            arguments.Add($"__a{j}");
        }

        for (var i = 0; i < model.Properties.Length; i++)
        {
            var property = model.Properties[i];

            if (property.Write == WriteKind.None)
            {
                continue;
            }

            var read = property.ConverterTypeName != null
                ? $"({property.TypeName}){ConverterField(property)}.Read(__t{i}, typeof({property.TypeOfName}), options)"
                : ReadExpression(property.Plan, $"__t{i}", "depth + 1");

            code.AppendLine();
            code.AppendLine($"{property.TypeName} __p{i} = default!;");
            code.AppendLine($"var __h{i} = false;");
            code.BeginBlock($"if (__obj.Properties.TryGetValue({NameExpression(property)}, out var __t{i}))");
            code.AppendLine($"__p{i} = {read};");
            code.AppendLine($"__h{i} = true;");
            code.EndBlock();
        }

        code.AppendLine();

        var initializers = model.Properties.Select((p, i) => (Property: p, Index: i))
                                .Where(p => p.Property.Write == WriteKind.Initializer)
                                .Select(p => $"{p.Property.Name} = __h{p.Index} ? __p{p.Index} : default!")
                                .ToList();

        var creation = $"new {model.FullyQualifiedName}({string.Join(", ", arguments)})";

        if (initializers.Count == 0)
        {
            code.AppendLine($"var __result = {creation};");
        }
        else
        {
            code.AppendLine($"var __result = {creation}");
            code.AppendLine("{");
            code.IncrementIndent();

            foreach (var initializer in initializers)
            {
                code.AppendLine(initializer + ",");
            }

            code.DecrementIndent();
            code.AppendLine("};");
        }

        for (var i = 0; i < model.Properties.Length; i++)
        {
            var property = model.Properties[i];

            switch (property.Write)
            {
                case WriteKind.Assign:
                    code.AppendLine($"if (__h{i}) __result.{property.Name} = __p{i};");
                    break;
                case WriteKind.Accessor:
                    var reference = property.SetterOwnerIsValueType ? "ref " : "";
                    code.AppendLine($"if (__h{i}) {AccessorName(property)}({reference}__result, __p{i});");
                    break;
            }
        }

        code.AppendLine();
        code.AppendLine("return __result;");
        code.EndBlock();
    }

    /// <summary>
    /// An expression reading a <c>ToonValue</c> as the plan's declared type. Exact string, boolean and number matches
    /// are converted inline; anything else goes through the helpers, which apply ToonSerializer's parsing and errors.
    /// </summary>
    private string ReadExpression(ValuePlan plan, string toon, string depth)
    {
        var n = _variable++;

        switch (plan.Kind)
        {
            case ValueKind.Inline:
            {
                var slow = $"{Helpers}.ReadPrimitive<{plan.TypeName}>({toon})";
                var type = plan.ValueTypeName;
                var d = $"__d{n}";
                var exactNumber = $"{toon} is {Models}ToonNumber {{ DecimalValue: {{ }} {d} }}";

                var (condition, value) = plan.Inline switch
                {
                    PrimitiveKind.String => ($"{toon} is {Models}ToonString __s{n}", $"__s{n}.Value"),
                    PrimitiveKind.Boolean => ($"{toon} is {Models}ToonBoolean __b{n}", $"__b{n}.Value"),
                    PrimitiveKind.Integer or PrimitiveKind.UInt64 =>
                        ($"{exactNumber} && {d} == decimal.Truncate({d}) && {d} >= {type}.MinValue && {d} <= {type}.MaxValue", $"({type}){d}"),
                    PrimitiveKind.Decimal => (exactNumber, d),
                    PrimitiveKind.Single => ($"{toon} is {Models}ToonNumber __n{n}", $"(float)__n{n}.Value"),
                    _ => ($"{toon} is {Models}ToonNumber __n{n}", $"__n{n}.Value")
                };

                return $"{condition} ? {value} : {slow}";
            }
            case ValueKind.Primitive:
                return $"{Helpers}.ReadPrimitive<{plan.TypeName}>({toon})";
            case ValueKind.Raw:
                return $"{toon} is {plan.ValueTypeName} __r{n} ? __r{n} : {Helpers}.DeserializeWithReflection<{plan.TypeName}>({toon}, options, {depth})";
            case ValueKind.Generated:
            {
                var call = $"{plan.ValueTypeName}.__ToonDeserializeValue({toon}, options, {depth})";
                return plan.IsNullableValueType ? $"{toon} is {Models}ToonNull ? default({plan.TypeName}) : {call}" : call;
            }
            case ValueKind.Reflection:
                return $"{Helpers}.DeserializeWithReflection<{plan.TypeName}>({toon}, options, {depth})";
            default:
                return $"{ReaderName(plan)}({toon}, options, {depth})";
        }
    }

    private void EmitAccessors()
    {
        foreach (var property in _model.Properties)
        {
            if (property.Write != WriteKind.Accessor)
            {
                continue;
            }

            var reference = property.SetterOwnerIsValueType ? "ref " : "";

            _code.AppendLine();
            _code.AppendLine("[global::System.Runtime.CompilerServices.UnsafeAccessor(" +
                             $"global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = \"set_{property.Name}\")]");
            _code.AppendLine($"private static extern void {AccessorName(property)}({reference}{property.SetterOwner} instance, {property.TypeName} value);");
        }
    }

    #endregion

    #region Collection and dictionary helpers

    private string WriterName(ValuePlan plan) => $"__ToonWrite{Register(_writerIds, _writers, plan.ValueTypeName, plan)}";

    private string ReaderName(ValuePlan plan) => $"__ToonRead{Register(_readerIds, _readers, plan.TypeName, plan)}";

    private static int Register(Dictionary<string, int> ids, List<(int, ValuePlan)> pending, string key, ValuePlan plan)
    {
        if (!ids.TryGetValue(key, out var id))
        {
            id = ids.Count;
            ids[key] = id;
            pending.Add((id, plan));
        }

        return id;
    }

    /// <summary>Emits the helper methods; emitting one can register more (nested collections), so loop until done.</summary>
    private void EmitHelperMethods()
    {
        for (int w = 0, r = 0; w < _writers.Count || r < _readers.Count;)
        {
            while (w < _writers.Count)
            {
                EmitWriter(_writers[w].Id, _writers[w++].Plan);
            }

            while (r < _readers.Count)
            {
                EmitReader(_readers[r].Id, _readers[r++].Plan);
            }
        }
    }

    private void EmitWriter(int id, ValuePlan plan)
    {
        var code = _code;
        var element = plan.Element!;

        code.AppendLine();
        code.BeginBlock($"private static {Models}ToonValue __ToonWrite{id}({plan.ValueTypeName} value, {Options} options, int depth)");
        code.AppendLine($"{Helpers}.CheckSerializationDepth(options, depth);");

        if (plan.Kind == ValueKind.Dictionary)
        {
            var key = plan.Key!.Inline == PrimitiveKind.String ? "__entry.Key" : $"{Helpers}.FormatKey(__entry.Key)";

            code.AppendLine($"var __obj = new {Models}ToonObject();");
            code.BeginBlock("foreach (var __entry in value)");
            code.AppendLine($"var __key = {key};");
            code.AppendLine("var __value = __entry.Value;");
            EmitStore("__obj.Properties[__key]", element, "__value", "depth + 1");
            code.EndBlock();
            code.AppendLine("return __obj;");
        }
        else
        {
            // Null items are always kept so that indexes are preserved, like ToonSerializer.
            var item = WriteExpression(element, NonNull(element, "__item"), "depth + 1");

            code.AppendLine($"var __array = new {Models}ToonArray();");
            code.BeginBlock("foreach (var __item in value)");
            code.AppendLine(element.CanBeNull
                                ? $"__array.Items.Add(__item is null ? {Models}ToonNull.Instance : {item});"
                                : $"__array.Items.Add({item});");
            code.EndBlock();
            code.AppendLine("return __array;");
        }

        code.EndBlock();
    }

    private void EmitReader(int id, ValuePlan plan)
    {
        var code = _code;
        var element = plan.Element!;
        var reflection = $"{Helpers}.DeserializeWithReflection<{plan.TypeName}>(value, options, depth)";

        code.AppendLine();
        code.BeginBlock($"private static {plan.TypeName} __ToonRead{id}({Models}ToonValue value, {Options} options, int depth)");
        code.AppendLine($"{Helpers}.CheckDeserializationDepth(options, depth);");

        if (plan.Kind == ValueKind.Dictionary)
        {
            var keyPlan = plan.Key!;
            var key = keyPlan.Inline == PrimitiveKind.String
                ? "__entry.Key"
                : $"{Helpers}.ReadPrimitive<{keyPlan.ValueTypeName}>(new {Models}ToonString(__entry.Key))";

            code.AppendLine($"if (value is not {Models}ToonObject __obj) return {reflection};");
            code.AppendLine($"var __dictionary = new global::System.Collections.Generic.Dictionary<{keyPlan.ValueTypeName}, {element.TypeName}>();");
            code.BeginBlock("foreach (var __entry in __obj.Properties)");
            code.AppendLine($"__dictionary[{key}] = {ReadExpression(element, "__entry.Value", "depth + 1")};");
            code.EndBlock();
            code.AppendLine("return __dictionary;");
        }
        else
        {
            code.AppendLine($"if (value is not {Models}ToonArray __array) return {reflection};");
            code.AppendLine($"var __items = new global::System.Collections.Generic.List<{element.TypeName}>(__array.Count);");
            code.BeginBlock("for (var __i = 0; __i < __array.Count; __i++)");
            code.AppendLine($"__items.Add({ReadExpression(element, "__array[__i]", "depth + 1")});");
            code.EndBlock();
            code.AppendLine(plan.Kind switch
            {
                ValueKind.Array => "return __items.ToArray();",
                ValueKind.Set => $"return new global::System.Collections.Generic.HashSet<{element.TypeName}>(__items);",
                _ => "return __items;"
            });
        }

        code.EndBlock();
    }

    #endregion

    private void EmitPolicyLocal()
    {
        if (_model.FixedNamingPolicy == null)
        {
            _code.AppendLine("var __policy = options.PropertyNamingPolicy;");
        }
    }

    /// <summary>
    /// The serialized key: the <c>[ToonProperty]</c> name, the attribute's fixed naming policy, or the naming policy
    /// of the options at runtime.
    /// </summary>
    private string NameExpression(PropertyModel property)
    {
        var names = property.Names;

        if (_model.FixedNamingPolicy is { } policy)
        {
            return Literal(names[policy is >= 0 and <= 3 ? policy : 0]);
        }

        if (names.Items.All(n => n == names[0]))
        {
            return Literal(names[0]);
        }

        const string policyType = Serialization + "PropertyNamingPolicy";

        if (names[1] == names[2] && names[2] == names[3])
        {
            return $"(__policy == {policyType}.Default ? {Literal(names[0])} : {Literal(names[1])})";
        }

        return $"(__policy switch {{ {policyType}.CamelCase => {Literal(names[1])}, {policyType}.SnakeCase => {Literal(names[2])}, " +
               $"{policyType}.LowerCase => {Literal(names[3])}, _ => {Literal(names[0])} }})";
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);

    private string Accessibility() => _model.PublicMethods ? "public" : "internal";

    private static string ConverterField(PropertyModel property) => $"__ToonConverter_{property.Name}";

    private static string AccessorName(PropertyModel property) => $"__ToonSet_{property.Name}";
}
